### ISSUE TITLE
Fix logging

### ISSUE THREAD

**Issue by mracine** [halibot-extra/emote#5]
The current code is not correctly calling the logging statements. This may need to be fixed along with general Halibot logging improvements.

**Comment by richteer** [comment]
Is this still an issue? I see proper use of `self.log`, and no calls to `print()`. Will close this otherwise.

**Comment by richteer** [comment]
I'm an idiot and pressed the wrong button. Ignore that.

**Comment by mracine** [comment]
Perhaps I should leave more descriptive bug information when writing an issue :P I don't remember my original intent but I believe it was as you described, replacing all `print()` statements with `self.log`. Closing this issue seeing as I see no current issues.
